name: CI/CD to AKS

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: myacrflask2040        # your Azure Container Registry name
  CLUSTER_NAME: myAKSCluster2040       # your AKS cluster name
  RESOURCE_GROUP: myResourceGroupFlask # your resource group name
  IMAGE_NAME: node-demo                # image name for your app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $REGISTRY_NAME

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.run_number }} .
          docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.run_number }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/node-demo node-demo=$REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.run_number }}
          kubectl rollout status deployment/node-demo
